/**
 * Filipino mahjong scoring patterns (common house standards).
 * Hands are typically 17 tiles: five melds (bahay) + one pair (eye).
 * Winds/dragons/flowers/seasons are often all treated as “flowers” (bonus).
 * Point values are illustrative — confirm your table’s sheet.
 */

window.FILIPINO_CATEGORY_META = {
  "going-out": { titleEn: "Going out" },
  chow: { titleEn: "Chow-based" },
  pung: { titleEn: "Pung-based" },
  suit: { titleEn: "Suit / special" },
  wait: { titleEn: "Waits" },
  flower: { titleEn: "Flowers & bonuses" },
};

window.FILIPINO_SECTION_META = {
  "1": { titleEn: "1 point" },
  "0.5": { titleEn: "½ point" },
  "0.25": { titleEn: "¼ point" },
  bonus: { titleEn: "Bonus / flowers" },
};

window.FILIPINO_DATA = [
  {
    id: "winning",
    nameEn: "Winning (Todas)",
    points: 1,
    section: "1",
    category: "going-out",
    tags: ["core"],
    description: "Base award for completing five melds and a pair (17 tiles).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 567C | 8B 8B" }],
  },
  {
    id: "all-chows",
    nameEn: "All Chows",
    points: 0.25,
    section: "0.25",
    category: "chow",
    tags: ["core"],
    description: "All five melds are sequences (no pungs/kongs).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 567C | 2B 2B" }],
  },
  {
    id: "all-pungs",
    nameEn: "All Pungs",
    points: 0.25,
    section: "0.25",
    category: "pung",
    tags: ["core"],
    description: "All five melds are pungs or kongs.",
    examples: [{ tiles: "111P | 222B | 333C | 444P | 555B | 6C 6C" }],
  },
  {
    id: "concealed",
    nameEn: "Concealed Hand",
    points: 0.25,
    section: "0.25",
    category: "going-out",
    tags: ["core"],
    description: "No open melds before winning.",
    examples: [{ tiles: "123P | 456P | 789B | 111C | 222C | 5B 5B" }],
  },
  {
    id: "all-revealed",
    nameEn: "All Revealed",
    points: 0.25,
    section: "0.25",
    category: "going-out",
    tags: ["core"],
    description: "Every meld exposed; waiting only on the pair.",
    examples: [{ tiles: "123P | 456B | 789C | 111P | 222B | 3C 3C" }],
  },
  {
    id: "quick-win",
    nameEn: "Quick Win",
    points: 0.25,
    section: "0.25",
    category: "going-out",
    tags: ["core"],
    description: "Win within the first few discards (often within 5; house-dependent).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 555C | 8B 8B" }],
  },
  {
    id: "pure-straight",
    nameEn: "Pure Straight",
    points: 0.5,
    section: "0.5",
    category: "chow",
    tags: ["core"],
    description: "123, 456, and 789 of the same suit among your melds.",
    examples: [{ tiles: "123P | 456P | 789P | 222B | 333C | 5B 5B" }],
  },
  {
    id: "full-flush",
    nameEn: "Full Flush",
    points: 0.5,
    section: "0.5",
    category: "suit",
    tags: ["core"],
    description: "All number tiles from a single suit (bonus tiles aside).",
    examples: [{ tiles: "123P | 456P | 789P | 222P | 333P | 5P 5P" }],
  },
  {
    id: "seven-pairs",
    nameEn: "Seven Pairs",
    points: 0.5,
    section: "0.5",
    category: "suit",
    tags: ["core"],
    description: "Seven pairs plus one pung (common Filipino special hand).",
    examples: [{ tiles: "11P | 22P | 33B | 44B | 55C | 66C | 77P | 888B" }],
  },
  {
    id: "difficult-wait",
    nameEn: "Difficult Wait",
    points: 0.25,
    section: "0.25",
    category: "wait",
    tags: ["core"],
    description: "Edge, middle, or single-tile wait (paníngit / single).",
    examples: [{ tiles: "123P | 456B | 789C | 111P | 222B | 4C 4C", label: "Pair wait example" }],
  },
  {
    id: "no-flowers-start",
    nameEn: "No Flowers (deal)",
    points: 0.25,
    section: "bonus",
    category: "flower",
    tags: ["bonus-flower"],
    description: "Dealt no flower/bonus tiles at the start (when winds/dragons count as flowers, tables vary).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 567C | 8B 8B" }],
  },
  {
    id: "flower-set",
    nameEn: "Flower Set",
    points: 0.5,
    section: "bonus",
    category: "flower",
    tags: ["bonus-flower"],
    description: "A numbered flower set (or a large flower count when winds/dragons are flowers).",
    examples: [
      { tiles: "F1 F2 F3 F4", label: "Classic flower set" },
      { tiles: "123P | 456B | 789C | 111P | 222B | 3C 3C", label: "With a winning hand" },
    ],
  },
  {
    id: "season-set",
    nameEn: "Season Set",
    points: 0.5,
    section: "bonus",
    category: "flower",
    tags: ["bonus-season"],
    description: "All four seasons (shown as F5–F8; blanks mode uses blank tiles).",
    examples: [{ tiles: "F5 F6 F7 F8", label: "Season set" }],
  },
  {
    id: "joker-eye",
    nameEn: "Joker Eye",
    points: 0.25,
    section: "0.25",
    category: "going-out",
    tags: ["core"],
    description: "Pair completed with a joker — usually self-draw only; jokers not used in exposed melds.",
    examples: [{ tiles: "123P | 456B | 789C | 111P | 222B | 5C J" }],
  },
];
