/**
 * Hong Kong / Cantonese mahjong scoring patterns (common table standards).
 * Faan values vary by house; this is a study aid, not a substitute for your table’s sheet.
 *
 * tags:
 *   core — always shown
 *   bonus-flower — uses flower tiles (F1–F4)
 *   bonus-season — uses season tiles (F5–F8); blanks mode renders these as X
 */

window.HK_CATEGORY_META = {
  basic: { titleEn: "Basic / timing" },
  suit: { titleEn: "Suit patterns" },
  honor: { titleEn: "Honors & winds" },
  special: { titleEn: "Special structures" },
  limit: { titleEn: "13 faan hands" },
  bonus: { titleEn: "Flowers & seasons" },
};

window.HK_SECTION_META = {
  "1-faan": { titleEn: "1 faan" },
  "2-faan": { titleEn: "2 faan" },
  "3-faan": { titleEn: "3 faan" },
  "4-faan": { titleEn: "4 faan" },
  "5-faan": { titleEn: "5–6 faan" },
  "7-faan": { titleEn: "7–8 faan" },
  "9-faan": { titleEn: "9 faan" },
  "13-faan": { titleEn: "13 faan" },
  bonus: { titleEn: "Bonus tiles" },
};

window.HK_DATA = [
  {
    id: "ping-wu",
    nameEn: "All Sequences",
    nameZh: "平胡",
    faan: 1,
    section: "1-faan",
    category: "basic",
    tags: ["core"],
    description: "All four melds are chows; no honor pungs/kongs. Often needs extras to meet a 3-faan minimum.",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 8C 8C" }],
  },
  {
    id: "dragon-pung",
    nameEn: "Dragon",
    nameZh: "番牌 / 三元牌",
    faan: 1,
    faanLabel: "1× faan",
    section: "1-faan",
    category: "honor",
    tags: ["core"],
    description: "Pung or kong of any dragon — 1 faan per dragon set (stack if you have more than one).",
    examples: [{ tiles: "RD RD RD | 123P | 456B | 789C | 2P 2P" }],
  },
  {
    id: "seat-wind",
    nameEn: "Seat Wind",
    nameZh: "門風",
    faan: 1,
    section: "1-faan",
    category: "honor",
    tags: ["core"],
    description: "Pung/kong of your own seat wind.",
    examples: [{ tiles: "EW EW EW | 234P | 567B | 789C | 3P 3P" }],
  },
  {
    id: "round-wind",
    nameEn: "Round Wind",
    nameZh: "圈風",
    faan: 1,
    section: "1-faan",
    category: "honor",
    tags: ["core"],
    description: "Pung/kong of the prevailing round wind.",
    examples: [{ tiles: "SW SW SW | 123B | 456C | 789P | 5B 5B" }],
  },
  {
    id: "self-draw",
    nameEn: "Self-Drawn",
    nameZh: "自摸",
    faan: 1,
    section: "1-faan",
    category: "basic",
    tags: ["core"],
    description: "Win by drawing from the wall (timing bonus; no fixed tile pattern).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 8C 8C", label: "Example structure + self-draw" }],
  },
  {
    id: "fully-concealed",
    nameEn: "Fully Concealed",
    nameZh: "門前清",
    faan: 1,
    section: "1-faan",
    category: "basic",
    tags: ["core"],
    description: "No exposed melds before winning (house definitions vary).",
    examples: [{ tiles: "123P | 456P | 789B | 234C | 5C 5C" }],
  },
  {
    id: "rob-kong",
    nameEn: "Robbing the Kong",
    nameZh: "搶槓",
    faan: 1,
    section: "1-faan",
    category: "basic",
    tags: ["core"],
    description: "Win by claiming a tile someone just added to promote a pung into a kong.",
    examples: [],
  },
  {
    id: "under-the-sea",
    nameEn: "Moon from the Bottom of the Sea",
    nameZh: "海底撈月",
    faan: 1,
    section: "1-faan",
    category: "basic",
    tags: ["core"],
    description: "Win by self-drawing the very last tile from the wall (last-tile draw).",
    examples: [],
  },
  {
    id: "no-flowers",
    nameEn: "No Flowers",
    nameZh: "無花",
    faan: 1,
    section: "1-faan",
    category: "bonus",
    tags: ["bonus-flower", "bonus-season"],
    description: "Win without having collected any flower or season tiles (when those bonuses are in play).",
    examples: [{ tiles: "123P | 456B | 789C | EW EW EW | 2P 2P" }],
  },
  {
    id: "voided-suit",
    nameEn: "Voided Suit",
    nameZh: "缺一門",
    faan: 2,
    section: "2-faan",
    category: "suit",
    tags: ["core"],
    description: "Hand uses only two of the three suits (plus honors if any).",
    examples: [{ tiles: "123P | 456P | 789B | 222B | EW EW" }],
  },
  {
    id: "three-concealed",
    nameEn: "Three Concealed Triplets",
    nameZh: "三暗刻",
    faan: 2,
    section: "2-faan",
    category: "special",
    tags: ["core"],
    description: "Three concealed pungs/kongs (fourth meld may be open).",
    examples: [{ tiles: "111P | 222B | 333C | 456P | 8B 8B" }],
  },
  {
    id: "kong-replacement",
    nameEn: "Win by Kong Replacement",
    nameZh: "槓上開花",
    faan: 2,
    section: "2-faan",
    category: "basic",
    tags: ["core"],
    description: "Win on the replacement tile drawn after declaring a kong.",
    examples: [],
  },
  {
    id: "all-pungs",
    nameEn: "All Triplets",
    nameZh: "對對胡",
    faan: 3,
    section: "3-faan",
    category: "special",
    tags: ["core"],
    description: "All four melds are pungs or kongs — no chows.",
    examples: [{ tiles: "111P | 444B | 777C | RD RD RD | 3P 3P" }],
  },
  {
    id: "half-flush",
    nameEn: "Mixed One Suit",
    nameZh: "混一色",
    faan: 3,
    section: "3-faan",
    category: "suit",
    tags: ["core"],
    description: "All suited tiles from one suit, plus honors allowed.",
    examples: [{ tiles: "123P | 456P | 789P | EW EW EW | RD RD" }],
  },
  {
    id: "mixed-terminals",
    nameEn: "Mixed Terminals",
    nameZh: "混么九",
    faan: 3,
    section: "3-faan",
    category: "special",
    tags: ["core"],
    description: "Only terminals (1/9) and honors.",
    examples: [{ tiles: "111P | 999B | 111C | EW EW EW | RD RD" }],
  },
  {
    id: "small-dragons",
    nameEn: "Small Three Dragons",
    nameZh: "小三元",
    faan: 5,
    section: "5-faan",
    category: "honor",
    tags: ["core"],
    description: "Pungs of two dragons and a pair of the third (dragon pung faan often stacked).",
    examples: [{ tiles: "RD RD RD | GD GD GD | WD WD | 456P | 2B 2B 2B" }],
  },
  {
    id: "seven-pairs",
    nameEn: "Seven Pairs",
    nameZh: "七對子",
    faan: 4,
    section: "4-faan",
    category: "special",
    tags: ["core"],
    description: "Seven pairs (house-dependent; not universal in classic HK lists).",
    examples: [{ tiles: "11P | 22P | 33B | 44B | 55C | 66C | EW EW" }],
  },
  {
    id: "small-winds",
    nameEn: "Small Four Winds",
    nameZh: "小四喜",
    faan: 6,
    section: "5-faan",
    category: "honor",
    tags: ["core"],
    description: "Pungs of three winds and a pair of the fourth.",
    examples: [{ tiles: "EW EW EW | SW SW SW | WW WW WW | NW NW | 5P 5P 5P" }],
  },
  {
    id: "full-flush",
    nameEn: "Full Flush",
    nameZh: "清一色",
    faan: 7,
    section: "7-faan",
    category: "suit",
    tags: ["core"],
    description: "Entire hand one suit — no honors.",
    examples: [{ tiles: "123P | 456P | 789P | 222P | 8P 8P" }],
  },
  {
    id: "all-concealed-triplets",
    nameEn: "All Concealed Triplets",
    nameZh: "坎坎胡",
    faan: 8,
    section: "7-faan",
    category: "special",
    tags: ["core"],
    description: "Four concealed pungs/kongs and a pair (no open melds; often implies all triplets).",
    examples: [{ tiles: "111P | 222B | 333C | 444P | 5B 5B" }],
  },
  {
    id: "big-dragons",
    nameEn: "Big Three Dragons",
    nameZh: "大三元",
    faan: 8,
    section: "7-faan",
    category: "honor",
    tags: ["core"],
    description: "Pung/kong of all three dragons.",
    examples: [{ tiles: "RD RD RD | GD GD GD | WD WD WD | 456P | 2B 2B" }],
  },
  {
    id: "double-kong-replacement",
    nameEn: "Double Kong Replacement",
    nameZh: "槓上槓",
    faan: 9,
    section: "9-faan",
    category: "basic",
    tags: ["core"],
    description: "Win on a replacement tile after a second kong in succession (kong → replacement → kong → win on that replacement). Values vary by table.",
    examples: [],
  },
  {
    id: "big-winds",
    nameEn: "Big Four Winds",
    nameZh: "大四喜",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "Pung/kong of all four winds.",
    examples: [{ tiles: "EW EW EW | SW SW SW | WW WW WW | NW NW NW | 5P 5P" }],
  },
  {
    id: "all-honors",
    nameEn: "All Honors",
    nameZh: "字一色",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "Only winds and dragons.",
    examples: [{ tiles: "EW EW EW | SW SW SW | RD RD RD | GD GD GD | WD WD" }],
  },
  {
    id: "all-terminals",
    nameEn: "All Terminals",
    nameZh: "清么九",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "Only terminal tiles (1s and 9s) — no honors and no simples.",
    examples: [{ tiles: "111P | 999P | 111B | 999B | 1C 1C" }],
  },
  {
    id: "thirteen-orphans",
    nameEn: "Thirteen Orphans",
    nameZh: "十三幺",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "One of each terminal and honor, plus a duplicate of any of them.",
    examples: [{ tiles: "1P 9P | 1B 9B | 1C 9C | EW SW WW NW | WD GD RD RD" }],
  },
  {
    id: "nine-gates",
    nameEn: "Nine Gates",
    nameZh: "九蓮寶燈",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "1112345678999 of one suit plus any extra tile of that suit.",
    examples: [{ tiles: "111P | 2345678P | 999P | 5P" }],
  },
  {
    id: "all-kongs",
    nameEn: "All Quadruplets",
    nameZh: "十八羅漢",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "Four kongs (quadruplets) and a pair.",
    examples: [{ tiles: "1111P | 2222B | 3333C | RD*4 | 5P 5P" }],
  },
  {
    id: "heavenly-hand",
    nameEn: "Blessing of Heaven",
    nameZh: "天胡",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "East (dealer) wins on the initial dealt hand before any discard.",
    examples: [],
  },
  {
    id: "earthly-hand",
    nameEn: "Blessing of Earth",
    nameZh: "地胡",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "A non-dealer wins on East’s first discard.",
    examples: [],
  },
  {
    id: "humanly-hand",
    nameEn: "Blessing of Man",
    nameZh: "人胡",
    faan: 13,
    section: "13-faan",
    category: "limit",
    tags: ["core"],
    description: "Win on the first discard from a non-dealer (house definitions vary; sometimes only the first claim of the deal).",
    examples: [],
  },
  {
    id: "flower-set",
    nameEn: "Complete Flower Set",
    nameZh: "花胡",
    faan: 1,
    section: "bonus",
    category: "bonus",
    tags: ["bonus-flower"],
    description: "Collect all four flower tiles (plum, orchid, chrysanthemum, bamboo). Values vary by table.",
    examples: [
      { tiles: "F1 F2 F3 F4", label: "Bonus set (not a full 14-tile hand)" },
      { tiles: "123P | 456B | 789C | EW EW EW | 2P 2P", label: "With a normal win" },
    ],
  },
  {
    id: "season-set",
    nameEn: "Complete Season Set",
    nameZh: "季花",
    faan: 1,
    section: "bonus",
    category: "bonus",
    tags: ["bonus-season"],
    description: "Collect all four season tiles. Use Settings → Seasons to include, exclude, or show as blanks.",
    examples: [
      { tiles: "F5 F6 F7 F8", label: "Season set (F5–F8)" },
      { tiles: "123P | 456B | 789C | RD RD RD | 3P 3P", label: "With a normal win" },
    ],
  },
  {
    id: "seat-flower",
    nameEn: "Seat Flower",
    nameZh: "正花",
    faan: 1,
    section: "bonus",
    category: "bonus",
    tags: ["bonus-flower"],
    description: "Flower matching your seat (house numbering varies).",
    examples: [{ tiles: "F1", label: "Example seat flower" }],
  },
];
