/**
 * Core + optional Riichi yaku. Descriptions compiled from common cheatsheet sources.
 * Notation: see tiles.js (e.g. 123P | 456P | 789P | EW EW | 55B)
 */

window.YAKU_DATA = [
  // ——— 1 han ———
  {
    id: "riichi",
    nameEn: "Ready Hand",
    nameJp: "立直",
    hanClosed: 1,
    hanOpen: null,
    closedOnly: true,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Declare riichi when reaching tenpai with a closed hand (1000-point bet).",
    examples: [],
  },
  {
    id: "ippatsu",
    nameEn: "One-Shot",
    nameJp: "一発",
    hanClosed: 1,
    hanOpen: null,
    closedOnly: true,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Win within the first uninterrupted turn after declaring riichi.",
    examples: [],
  },
  {
    id: "tsumo",
    nameEn: "Fully Concealed Hand",
    nameJp: "門前清自摸和",
    hanClosed: 1,
    hanOpen: null,
    closedOnly: true,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Win by self-draw with a fully closed hand.",
    examples: [],
  },
  {
    id: "pinfu",
    nameEn: "Pinfu",
    nameJp: "平和",
    hanClosed: 1,
    hanOpen: null,
    closedOnly: true,
    section: "1-han",
    category: "sequence",
    tags: ["core"],
    description: "All sequences; valueless pair; open-wait (ryanmen). Closed only.",
    examples: [
      { label: "", tiles: "123P | 456P | 789B | 234C | 8C 8C" },
    ],
  },
  {
    id: "iipeikou",
    nameEn: "Pure Double Sequence",
    nameJp: "一盃口",
    hanClosed: 1,
    hanOpen: null,
    closedOnly: true,
    section: "1-han",
    category: "sequence",
    tags: ["core"],
    description: "Two identical sequences in the same suit. Closed only.",
    examples: [
      { label: "", tiles: "223344P | 567B | 123C | EW EW" },
    ],
  },
  {
    id: "tanyao",
    nameEn: "All Simples",
    nameJp: "断么九",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "terminals",
    tags: ["core"],
    description: "Hand contains only 2–8 suit tiles (no terminals or honors).",
    examples: [
      { label: "", tiles: "234B | 567P | 888C | 33P | 2B 2B 2B" },
    ],
  },
  {
    id: "yakuhai-haku",
    nameEn: "White Dragon",
    nameJp: "役牌 白",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "triplet",
    tags: ["core"],
    description: "Triplet/quad of white dragons.",
    examples: [
      { label: "", tiles: "WD WD WD | 123P | 456B | 789C | 2C 2C" },
    ],
  },
  {
    id: "yakuhai-hatsu",
    nameEn: "Green Dragon",
    nameJp: "役牌 發",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "triplet",
    tags: ["core"],
    description: "Triplet/quad of green dragons.",
    examples: [
      { label: "", tiles: "GD GD GD | 123P | 456B | 789C | 2C 2C" },
    ],
  },
  {
    id: "yakuhai-chun",
    nameEn: "Red Dragon",
    nameJp: "役牌 中",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "triplet",
    tags: ["core"],
    description: "Triplet/quad of red dragons.",
    examples: [
      { label: "", tiles: "RD RD RD | 123P | 456B | 789C | 2C 2C" },
    ],
  },
  {
    id: "yakuhai-wind",
    nameEn: "Seat / Round Wind",
    nameJp: "自風・場風",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "triplet",
    tags: ["core"],
    description: "Triplet of your seat wind and/or the round (prevalent) wind. Each qualifies separately.",
    examples: [
      { label: "East (example)", tiles: "EW EW EW | 123P | 456B | 789C | 2C 2C" },
    ],
  },
  {
    id: "rinshan",
    nameEn: "After a Kan",
    nameJp: "嶺上開花",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Win on the replacement tile after declaring a kan.",
    examples: [],
  },
  {
    id: "chankan",
    nameEn: "Robbing a Kan",
    nameJp: "搶槓",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Ron when another player adds a tile to an open pung to make a kan.",
    examples: [],
  },
  {
    id: "haitei",
    nameEn: "Under the Sea",
    nameJp: "海底摸月",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Win by tsumo on the last draw from the wall.",
    examples: [],
  },
  {
    id: "houtei",
    nameEn: "Under the River",
    nameJp: "河底撈魚",
    hanClosed: 1,
    hanOpen: 1,
    closedOnly: false,
    section: "1-han",
    category: "lucky",
    tags: ["core"],
    description: "Win by ron on the last discard of the hand.",
    examples: [],
  },

  // ——— 2 han ———
  {
    id: "double-riichi",
    nameEn: "Double Riichi",
    nameJp: "両立直",
    hanClosed: 2,
    hanOpen: null,
    closedOnly: true,
    section: "2-han",
    category: "lucky",
    tags: ["core"],
    description: "Riichi declared on the first turn before any calls interrupt.",
    examples: [],
  },
  {
    id: "chiitoitsu",
    nameEn: "Seven Pairs",
    nameJp: "七対子",
    hanClosed: 2,
    hanOpen: null,
    closedOnly: true,
    section: "2-han",
    category: "special",
    tags: ["core"],
    description: "Seven distinct pairs. Closed only. No four-of-a-kind as two pairs.",
    examples: [
      { label: "", tiles: "1P 1P | 3P 3P | 5B 5B | 7B 7B | 2C 2C | 8C 8C | WD WD" },
    ],
  },
  {
    id: "sanshoku-doujun",
    nameEn: "Three Color Straight",
    nameJp: "三色同順",
    hanClosed: 2,
    hanOpen: 1,
    closedOnly: false,
    section: "2-han",
    category: "sequence",
    tags: ["core"],
    description: "Same numbered sequence in all three suits.",
    examples: [
      { label: "234", tiles: "234P | 234B | 234C | 789P | EW EW" },
    ],
  },
  {
    id: "ittsu",
    nameEn: "Pure Straight",
    nameJp: "一気通貫",
    hanClosed: 2,
    hanOpen: 1,
    closedOnly: false,
    section: "2-han",
    category: "sequence",
    tags: ["core"],
    description: "123 + 456 + 789 sequences in one suit.",
    examples: [
      { label: "Pinzu", tiles: "123P | 456P | 789P | 22B | 345C" },
      { label: "Souzu", tiles: "123B | 456B | 789B | WD WD | 678P" },
    ],
  },
  {
    id: "chanta",
    nameEn: "Half Outside Hand",
    nameJp: "混全帯么九",
    hanClosed: 2,
    hanOpen: 1,
    closedOnly: false,
    section: "2-han",
    category: "terminals",
    tags: ["core"],
    description: "Every set and the pair contains a terminal (1/9) or honor.",
    examples: [
      { label: "", tiles: "123P | 789B | 111C | EW EW EW | RD RD" },
    ],
  },
  {
    id: "sanshoku-doukou",
    nameEn: "Three Color Triplets",
    nameJp: "三色同刻",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "triplet",
    tags: ["core"],
    description: "Same-number triplets in all three suits.",
    examples: [
      { label: "5s", tiles: "5P 5P 5P | 5B 5B 5B | 5C 5C 5C | 123P | EW EW" },
    ],
  },
  {
    id: "sanankou",
    nameEn: "Three Concealed Triplets",
    nameJp: "三暗刻",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "triplet",
    tags: ["core"],
    description: "Three concealed triplets/quads (the rest of the hand may be open).",
    examples: [
      { label: "", tiles: "1P 1P 1P | 5B 5B 5B | 8C 8C 8C | 234P | WD WD" },
    ],
  },
  {
    id: "sankantsu",
    nameEn: "Three Quads",
    nameJp: "三槓子",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "triplet",
    tags: ["core"],
    description: "Three kans (quads) in one hand.",
    examples: [
      {
        label: "",
        tiles: "1P 1P 1P 1P | 5B 5B 5B 5B | EW EW EW EW | 234C | 8C 8C",
      },
    ],
  },
  {
    id: "toitoi",
    nameEn: "All Triplets",
    nameJp: "対々和",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "triplet",
    tags: ["core"],
    description: "Four triplets/quads and a pair.",
    examples: [
      { label: "", tiles: "1P 1P 1P | 5B 5B 5B | 8C 8C 8C | EW EW EW | RD RD" },
    ],
  },
  {
    id: "shousangen",
    nameEn: "Little Three Dragons",
    nameJp: "小三元",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "triplet",
    tags: ["core"],
    description: "Two dragon triplets and a pair of the third dragon (+ yakuhai from the triplets).",
    examples: [
      { label: "", tiles: "WD WD WD | GD GD GD | RD RD | 123P | 456B" },
    ],
  },
  {
    id: "honroutou",
    nameEn: "All Terminals and Honors",
    nameJp: "混老頭",
    hanClosed: 2,
    hanOpen: 2,
    closedOnly: false,
    section: "2-han",
    category: "terminals",
    tags: ["core"],
    description: "Only 1s, 9s, and honors (always combines with toitoi or chiitoitsu).",
    examples: [
      { label: "Toitoi form", tiles: "1P 1P 1P | 9B 9B 9B | 1C 1C 1C | EW EW EW | RD RD" },
    ],
  },

  // ——— 3 han ———
  {
    id: "ryanpeikou",
    nameEn: "Twice Pure Double Sequence",
    nameJp: "二盃口",
    hanClosed: 3,
    hanOpen: null,
    closedOnly: true,
    section: "3-han",
    category: "sequence",
    tags: ["core"],
    description: "Two iipeikou (two pairs of identical sequences). Closed only. Does not stack with chiitoitsu.",
    examples: [
      { label: "", tiles: "223344P | 556677B | 8C 8C" },
    ],
  },
  {
    id: "junchan",
    nameEn: "Pure Outside Hand",
    nameJp: "純全帯么九",
    hanClosed: 3,
    hanOpen: 2,
    closedOnly: false,
    section: "3-han",
    category: "terminals",
    tags: ["core"],
    description: "Every set and the pair contains a terminal; no honors.",
    examples: [
      { label: "", tiles: "123P | 789P | 111B | 999C | 9B 9B" },
    ],
  },
  {
    id: "honitsu",
    nameEn: "Half Flush",
    nameJp: "混一色",
    hanClosed: 3,
    hanOpen: 2,
    closedOnly: false,
    section: "3-han",
    category: "flush",
    tags: ["core"],
    description: "One suit plus honors only.",
    examples: [
      { label: "Pin + honors", tiles: "123P | 456P | 789P | EW EW EW | RD RD" },
      { label: "Sou + honors", tiles: "111B | 456B | 789B | WD WD WD | NW NW" },
    ],
  },

  // ——— 6 han ———
  {
    id: "chinitsu",
    nameEn: "Full Flush",
    nameJp: "清一色",
    hanClosed: 6,
    hanOpen: 5,
    closedOnly: false,
    section: "6-han",
    category: "flush",
    tags: ["core"],
    description: "All tiles in a single suit (no honors).",
    examples: [
      { label: "Pinzu", tiles: "123P | 456P | 789P | 22P | 333P" },
      { label: "Manzu", tiles: "111C | 234C | 567C | 789C | 9C 9C" },
      { label: "Souzu", tiles: "123B | 456B | 789B | 22B | 888B" },
    ],
  },

  // ——— Yakuman ———
  {
    id: "kokushi",
    nameEn: "Thirteen Orphans",
    nameJp: "国士無双",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "One of each terminal and honor, plus a duplicate of any of them. Closed only.",
    examples: [
      { label: "", tiles: "1P 9P | 1B 9B | 1C 9C | EW SW WW NW | WD GD RD RD" },
    ],
  },
  {
    id: "suuankou",
    nameEn: "Four Concealed Triplets",
    nameJp: "四暗刻",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Four concealed triplets and a pair. Closed; ron only valid on pair wait (tanki) under many rules.",
    examples: [
      { label: "", tiles: "1P 1P 1P | 5B 5B 5B | 8C 8C 8C | EW EW EW | RD RD" },
    ],
  },
  {
    id: "daisangen",
    nameEn: "Big Three Dragons",
    nameJp: "大三元",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Triplets of all three dragons.",
    examples: [
      { label: "", tiles: "WD WD WD | GD GD GD | RD RD RD | 123P | 2B 2B" },
    ],
  },
  {
    id: "shousuushii",
    nameEn: "Little Four Winds",
    nameJp: "小四喜",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Three wind triplets and a pair of the fourth wind.",
    examples: [
      { label: "", tiles: "EW EW EW | SW SW SW | WW WW WW | NW NW | 123P" },
    ],
  },
  {
    id: "daisuushii",
    nameEn: "Big Four Winds",
    nameJp: "大四喜",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core", "double-yakuman"],
    description: "Triplets of all four winds. Often scored as double yakuman (Settings).",
    examples: [
      { label: "", tiles: "EW EW EW | SW SW SW | WW WW WW | NW NW NW | 5P 5P" },
    ],
  },
  {
    id: "tsuuiisou",
    nameEn: "All Honors",
    nameJp: "字一色",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Hand consists only of honor tiles.",
    examples: [
      { label: "", tiles: "EW EW EW | SW SW SW | WD WD WD | GD GD GD | RD RD" },
    ],
  },
  {
    id: "chinroutou",
    nameEn: "All Terminals",
    nameJp: "清老頭",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Only 1s and 9s (no honors).",
    examples: [
      { label: "", tiles: "1P 1P 1P | 9P 9P 9P | 1B 1B 1B | 9C 9C 9C | 1C 1C" },
    ],
  },
  {
    id: "ryuuiisou",
    nameEn: "All Green",
    nameJp: "緑一色",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Only green tiles: 2,3,4,6,8 sou and/or green dragon.",
    examples: [
      { label: "", tiles: "234B | 234B | 6B 6B | 8B 8B 8B | GD GD GD" },
    ],
  },
  {
    id: "chuuren",
    nameEn: "Nine Gates",
    nameJp: "九蓮宝燈",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "1112345678999 in one suit plus one extra tile of that suit. Closed only.",
    examples: [
      { label: "Pinzu + 5", tiles: "1P 1P 1P | 2P 3P 4P | 5P 5P | 6P 7P 8P | 9P 9P 9P" },
    ],
  },
  {
    id: "suukantsu",
    nameEn: "Four Quads",
    nameJp: "四槓子",
    hanClosed: "yakuman",
    hanOpen: "yakuman",
    closedOnly: false,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Four kans and a pair.",
    examples: [
      {
        label: "",
        tiles: "1P 1P 1P 1P | 5B 5B 5B 5B | 8C 8C 8C 8C | EW EW EW EW | RD RD",
      },
    ],
  },
  {
    id: "tenhou",
    nameEn: "Blessing of Heaven",
    nameJp: "天和",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Dealer wins on the initial deal (before any discards).",
    examples: [],
  },
  {
    id: "chiihou",
    nameEn: "Blessing of Earth",
    nameJp: "地和",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "yakuman",
    category: "yakuman",
    tags: ["core"],
    description: "Non-dealer wins by tsumo on the first draw (uninterrupted).",
    examples: [],
  },

  // ——— Optional ———
  {
    id: "nagashi",
    nameEn: "Nagashi Mangan",
    nameJp: "流し満貫",
    hanClosed: "mangan",
    hanOpen: "mangan",
    closedOnly: false,
    section: "optional",
    category: "lucky",
    tags: ["optional"],
    description: "At exhaustive draw, all of your discards were terminals/honors and none were called. Scored as mangan (rules vary).",
    examples: [],
  },
  {
    id: "renhou",
    nameEn: "Blessing of Man",
    nameJp: "人和",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "optional",
    category: "yakuman",
    tags: ["optional"],
    description: "Non-dealer wins by ron on a discard in the first uninterrupted turn set. Optional; value varies (yakuman / mangan).",
    examples: [],
  },
  {
    id: "kokushi-13",
    nameEn: "Thirteen Orphans (13-wait)",
    nameJp: "国士無双十三面待ち",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "optional",
    category: "yakuman",
    tags: ["optional", "double-yakuman"],
    description: "Kokushi waiting on all 13 orphans. Often double yakuman when enabled.",
    examples: [
      { label: "13-way wait shape", tiles: "1P 9P | 1B 9B | 1C 9C | EW SW WW NW | WD GD RD" },
    ],
  },
  {
    id: "suuankou-tanki",
    nameEn: "Four Concealed Triplets (Pair Wait)",
    nameJp: "四暗刻単騎",
    hanClosed: "yakuman",
    hanOpen: null,
    closedOnly: true,
    section: "optional",
    category: "yakuman",
    tags: ["optional", "double-yakuman"],
    description: "Suuankou completed on a pair wait. Often double yakuman when enabled.",
    examples: [
      { label: "", tiles: "1P 1P 1P | 5B 5B 5B | 8C 8C 8C | EW EW EW | RD" },
    ],
  },
];

window.SCORING_REF = {
  title: "Scoring quick reference",
  limits: [
    { name: "Mangan", han: "5 han (or 4 han 40+ fu / 3 han 70+ fu)", dealerTsumo: "4000 all", dealerRon: "12000", nonDealerRon: "8000" },
    { name: "Haneman", han: "6–7 han", dealerTsumo: "6000 all", dealerRon: "18000", nonDealerRon: "12000" },
    { name: "Baiman", han: "8–10 han", dealerTsumo: "8000 all", dealerRon: "24000", nonDealerRon: "16000" },
    { name: "Sanbaiman", han: "11–12 han", dealerTsumo: "12000 all", dealerRon: "36000", nonDealerRon: "24000" },
    { name: "Yakuman", han: "13+ / yakuman", dealerTsumo: "16000 all", dealerRon: "48000", nonDealerRon: "32000" },
  ],
  notes: [
    "Dora, ura-dora, and aka-dora add han but are not yaku.",
    "Kazoe yakuman: 13+ han may count as yakuman (ruleset-dependent).",
    "Fu is omitted on this sheet; use a fu chart when needed.",
  ],
};

window.SECTION_META = {
  "1-han": { titleEn: "1 Han", titleJp: "1翻" },
  "2-han": { titleEn: "2 Han", titleJp: "2翻" },
  "3-han": { titleEn: "3 Han", titleJp: "3翻" },
  "6-han": { titleEn: "6 Han", titleJp: "6翻" },
  yakuman: { titleEn: "Yakuman", titleJp: "役満" },
  optional: { titleEn: "Optional / Local", titleJp: "ローカル役" },
};

window.CATEGORY_META = {
  sequence: { titleEn: "Sequences", titleJp: "順子系" },
  triplet: { titleEn: "Triplets & Honors", titleJp: "刻子・役牌" },
  flush: { titleEn: "Flush Hands", titleJp: "一色系" },
  terminals: { titleEn: "Terminals & Simples", titleJp: "么九・断么" },
  lucky: { titleEn: "Lucky / Timing", titleJp: "状況役" },
  special: { titleEn: "Special Shapes", titleJp: "特殊形" },
  yakuman: { titleEn: "Yakuman", titleJp: "役満" },
};
